import { useEffect, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { QRCodeSVG } from 'qrcode.react'
import { api } from '../../lib/api'
import { useActiveMemberDetails } from '../../hooks/useFamily'

// ── Types ──────────────────────────────────────────────────────────────────

interface PassportResponse {
  passport_id: string
  member_id: string
  share_token: string
  expires_at: string | null
  is_active: boolean
  show_medications: boolean
  show_labs: boolean
  show_diagnoses: boolean
  show_allergies: boolean
  created_at: string | null
  access_count: number
}

interface PassportListResponse {
  items: PassportResponse[]
  total: number
}

interface PassportCreate {
  member_id: string
  expires_in_days: number
  show_medications: boolean
  show_labs: boolean
  show_diagnoses: boolean
  show_allergies: boolean
}

// ── Helpers ────────────────────────────────────────────────────────────────

function passportUrl(shareToken: string): string {
  return `${window.location.origin}/passport/${shareToken}`
}

function formatDate(iso: string | null): string {
  if (!iso) return '—'
  return new Date(iso).toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

// ── PassportManagePage ─────────────────────────────────────────────────────

export function PassportManagePage() {
  const queryClient = useQueryClient()
  const { member } = useActiveMemberDetails()
  const memberId = member?.member_id
  const autoGeneratedRef = useRef(false)
  const [copiedId, setCopiedId] = useState(false)
  const [copiedLink, setCopiedLink] = useState(false)

  const { data: passportData, isLoading, isError } = useQuery<PassportListResponse>({
    queryKey: ['passports', memberId],
    queryFn: async () => {
      const { data } = await api.get('/passport/', { params: { member_id: memberId } })
      return data
    },
    enabled: !!memberId,
  })

  const createMutation = useMutation<PassportResponse, Error, PassportCreate>({
    mutationFn: async (payload) => {
      const { data } = await api.post('/passport/', payload)
      return data
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ['passports', memberId] })
    },
  })

  // Auto-generate a permanent passport if none exists
  useEffect(() => {
    if (
      !isLoading &&
      !isError &&
      memberId &&
      passportData?.items.length === 0 &&
      !autoGeneratedRef.current &&
      !createMutation.isPending
    ) {
      autoGeneratedRef.current = true
      createMutation.mutate({
        member_id: memberId,
        expires_in_days: 3650, // 10 years ≈ permanent
        show_medications: true,
        show_labs: true,
        show_diagnoses: true,
        show_allergies: true,
      })
    }
  }, [isLoading, isError, memberId, passportData?.items.length])

  const passport = passportData?.items.find((p) => p.is_active) ?? null

  async function copyPassportId() {
    if (!passport) return
    await navigator.clipboard.writeText(passport.passport_id)
    setCopiedId(true)
    setTimeout(() => setCopiedId(false), 2000)
  }

  async function copyLink() {
    if (!passport) return
    await navigator.clipboard.writeText(passportUrl(passport.share_token))
    setCopiedLink(true)
    setTimeout(() => setCopiedLink(false), 2000)
  }

  const isReady = !isLoading && !isError && passport !== null

  return (
    <div className="max-w-2xl mx-auto px-4 py-8 space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-extrabold text-on-surface tracking-tight">Health Passport</h1>
        <p className="text-sm text-on-surface-variant mt-1">
          Share your Passport ID with any doctor so they can request access to your records.
        </p>
      </div>

      {/* Loading */}
      {(isLoading || createMutation.isPending) && (
        <div className="bg-white rounded-2xl shadow-sm border border-surface-container-low p-10 flex flex-col items-center gap-3">
          <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
          <p className="text-sm text-on-surface-variant">Setting up your passport…</p>
        </div>
      )}

      {/* Error */}
      {isError && (
        <div className="rounded-xl bg-error-container px-5 py-4 text-sm text-error font-medium">
          Failed to load passport data. Please try again.
        </div>
      )}

      {/* Main card */}
      {isReady && (
        <div className="bg-white rounded-2xl shadow-sm border border-surface-container-low overflow-hidden">
          {/* Identity header */}
          <div className="bg-gradient-to-r from-primary to-teal-700 px-6 py-5 text-white">
            <p className="text-xs font-semibold uppercase tracking-widest opacity-70 mb-1">
              Health Passport
            </p>
            <p className="text-xl font-extrabold leading-tight">{member?.full_name ?? '—'}</p>
            {member?.date_of_birth && (
              <p className="text-sm opacity-80 mt-0.5">{formatDate(member.date_of_birth)}</p>
            )}
            {member?.blood_group && (
              <span className="inline-block mt-2 px-2.5 py-0.5 rounded-full bg-white/20 text-white text-xs font-bold">
                {member.blood_group}
              </span>
            )}
          </div>

          <div className="p-6 space-y-6">
            {/* Passport ID — the key field */}
            <div>
              <p className="text-xs font-semibold text-on-surface-variant uppercase tracking-wide mb-2">
                Your Passport ID
              </p>
              <div className="flex items-start gap-3 bg-surface-container-low rounded-xl px-4 py-3">
                <p className="font-mono text-sm font-bold text-on-surface tracking-wider break-all flex-1 leading-relaxed">
                  {passport.passport_id}
                </p>
                <button
                  type="button"
                  onClick={copyPassportId}
                  className="shrink-0 inline-flex items-center gap-1.5 min-h-[36px] px-3 rounded-lg bg-primary text-white text-xs font-semibold hover:bg-primary/90 transition-colors"
                >
                  {copiedId ? (
                    <>
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="w-3.5 h-3.5">
                        <path d="M20 6 9 17l-5-5" />
                      </svg>
                      Copied!
                    </>
                  ) : (
                    <>
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="w-3.5 h-3.5">
                        <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
                        <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
                      </svg>
                      Copy
                    </>
                  )}
                </button>
              </div>
              <p className="text-xs text-on-surface-variant mt-2">
                Tell this ID to your doctor. They'll enter it on their end to request access to your records.
              </p>
            </div>

            {/* QR Code + share link */}
            <div className="flex flex-col sm:flex-row items-start gap-6">
              <div className="shrink-0 p-3 bg-white rounded-xl shadow-[0_0_0_1px_rgba(0,107,95,0.12)]">
                <QRCodeSVG
                  value={passportUrl(passport.share_token)}
                  size={140}
                  fgColor="#006b5f"
                  bgColor="#ffffff"
                  level="M"
                />
              </div>

              <div className="flex-1 space-y-3">
                <div>
                  <p className="text-xs font-semibold text-on-surface-variant uppercase tracking-wide mb-1">
                    Shareable Link
                  </p>
                  <p className="text-xs text-on-surface-variant break-all">
                    {passportUrl(passport.share_token)}
                  </p>
                </div>
                <button
                  type="button"
                  onClick={copyLink}
                  className="inline-flex items-center gap-2 min-h-[40px] px-4 rounded-xl bg-primary/10 text-primary text-sm font-semibold hover:bg-primary/20 transition-colors"
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="w-4 h-4">
                    <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
                    <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
                  </svg>
                  {copiedLink ? 'Copied!' : 'Copy Link'}
                </button>

                <div className="flex gap-4 text-xs text-on-surface-variant pt-1">
                  <div>
                    <span className="font-semibold">{passport.access_count}</span> access{passport.access_count !== 1 ? 'es' : ''}
                  </div>
                  {passport.expires_at && (
                    <div>Expires {formatDate(passport.expires_at)}</div>
                  )}
                </div>
              </div>
            </div>

            {/* What's included */}
            <div>
              <p className="text-xs font-semibold text-on-surface-variant uppercase tracking-wide mb-2">
                Included in your passport
              </p>
              <div className="flex flex-wrap gap-2">
                {[
                  { label: 'Medications', enabled: passport.show_medications },
                  { label: 'Lab Results', enabled: passport.show_labs },
                  { label: 'Diagnoses', enabled: passport.show_diagnoses },
                  { label: 'Allergies', enabled: passport.show_allergies },
                ].map(({ label, enabled }) => (
                  <span
                    key={label}
                    className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ${
                      enabled
                        ? 'bg-primary/10 text-primary'
                        : 'bg-surface-container text-on-surface-variant/50 line-through'
                    }`}
                  >
                    {enabled && (
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="w-3 h-3">
                        <path d="M20 6 9 17l-5-5" />
                      </svg>
                    )}
                    {label}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
